name: Sync


on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "https://github.com/CNMJH/cnmjh"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "https://gitee.com/cnmjh/cnmjh"


    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: cnmjh
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: sihuo666
          # 注意替换为你的 Gitee 仓库
          gitee-repo: cnmjh/cnmjh
-----------------------------------
©著作权归作者所有：来自51CTO博客作者Doocs的原创作品，请联系作者获取转载授权，否则将追究法律责任
一款实用的 GitHub Actions 小工具：Gitee Pages Actions
https://blog.51cto.com/u_12351456/5081146
